Parameterize Openstack Taster
osuosl/openstack_taster pull request #13
Opened 2017-06-22 17:23 UTC by DesertBeagle

This PR changes openstack taster so that it takes image names as a parameter.
Taster can now only operate on one image at a time, but can choose which test suites to use in addition.
There is a help flag as well as a flag to create the image upon test failure.

2017-06-22 18:12 UTC, knightsamar requested changes
```
for x in (openstack image list --quote all -f csv -c Name --public);
openstack_taster volumes $x; 
end
``` 
fish equivalent of the following bash
```
for x in $(openstack image list --quote all -f csv -c Name --public); do openstack_taster volumes $x; done
``` 
does not seem to work. Why?

edit: added bash

2017-06-22 18:12 UTC, knightsamar commented on bin/openstack_taster
> +}
The descriptions need to be swapped

2017-06-22 18:12 UTC, knightsamar commented on bin/openstack_taster
> +  opts.on('-c', '--create-image', 'Create image upon test failure. Used when testing.') do
"_Useful_ when testing" would be a better description.

2017-06-22 18:57 UTC, DesertBeagle commented
@knightsamar Merged taste into test, changed `test_*` into `taste_*`, and fixed option descriptions.

2017-06-22 18:58 UTC, knightsamar commented
Does it do a sane run ?

2017-06-22 20:43 UTC, DesertBeagle commented
@knightsamar Ready for review!

2017-06-22 22:14 UTC, knightsamar commented
That bash/fish script seems to have it's own problems due to the way how bash interprets it.

2017-06-22 22:15 UTC, knightsamar approved these changes
Good work!

2017-06-22 22:15 UTC, knightsamar requested changes
rubocop fixes please :)

2017-06-22 22:15 UTC, DesertBeagle commented
Great! I am going to squash real quick before I merge.

2017-06-22 23:09 UTC, DesertBeagle commented
@knightsamar Fixed rubocop errors!

2017-06-23 23:57 UTC, knightsamar approved these changes

2017-06-26 18:11 UTC, knightsamar commented
Merging this since it's great!

2017-06-26 18:11 UTC, merged