Fix option ordering and help text
osuosl/openstack_taster pull request #16
Opened 2017-06-27 16:36 UTC by DesertBeagle

2017-06-27 19:17 UTC, knightsamar requested changes

2017-06-27 19:17 UTC, knightsamar commented on bin/openstack_taster
>                  '   or: openstack_taster <option>'
This won't work anymore, right?

2017-06-27 19:26 UTC, DesertBeagle commented on bin/openstack_taster
>                  '   or: openstack_taster <option>'
This will work for `--help`, but if they attempt to use `--create-snapshot` it will throw an error.

2017-06-27 19:29 UTC, knightsamar commented on bin/openstack_taster
>                  '   or: openstack_taster <option>'
Ok, let's keep it here for future purposes.

2017-06-27 19:30 UTC, knightsamar commented
Please increment the patch version by 1 and we are good to merge!

2017-06-27 19:52 UTC, DesertBeagle commented
@knightsamar Bumped!

2017-06-27 20:26 UTC, knightsamar commented on bin/openstack_taster
>      settings[:create] = true
Can we please name this symbol aptly?

2017-06-27 21:13 UTC, DesertBeagle commented on bin/openstack_taster
>      settings[:create] = true
What is your suggestion?

2017-06-27 21:50 UTC, knightsamar commented on bin/openstack_taster
>      settings[:create] = true
`settings[:create_snapshot]` ?

2017-06-27 21:52 UTC, DesertBeagle commented on bin/openstack_taster
>      settings[:create] = true
Oh, that's what you mean. Sorry I wasn't looking at that. Sure thing!

2017-06-27 23:05 UTC, DesertBeagle commented
@knightsamar Ready!

2017-06-28 22:05 UTC, knightsamar approved these changes

2017-06-28 22:21 UTC, merged