Documenting most of OpenStack Taster in YARD
osuosl/openstack_taster pull request #19
Opened 2017-06-27 19:50 UTC by DesertBeagle

2017-06-27 21:49 UTC, knightsamar requested changes

2017-06-27 21:49 UTC, knightsamar commented on CONTRIBUTING.md
> +  1. Add a suite name and description to the `suites` hash. Do not use spaces.
You will need 4 spaces to make the sub-level formatting work.

2017-06-27 21:49 UTC, knightsamar commented on CONTRIBUTING.md
> +  3. Add your function to `lib/openstack_taste.rb`. The standard for suite function names is `taste_<suite_name>`.
`openstack_taster.rb` - *r* is missing.

2017-06-27 21:49 UTC, knightsamar commented on lib/openstack_taster.rb
> +  # @note This method blocks until the image is complete on the server.
do you mean "snapshot creation" is complete on the server ?

2017-06-27 21:49 UTC, knightsamar commented on lib/openstack_taster.rb
> +  #   creating a naming standard for test functionions (i.e. taste_<name>)
"functions" :)

2017-06-27 21:49 UTC, knightsamar commented on lib/openstack_taster.rb
> +  # @todo Don't crash when connection refused.
Does it really crash ? I never saw this.

2017-06-27 21:49 UTC, knightsamar commented on lib/openstack_taster.rb
> +  #   and passing the standardized parameters.
These ideas are already done, right ?  We probably just need to document it as a standard in the CONTRIBUTING doc.

2017-06-27 21:53 UTC, DesertBeagle commented on lib/openstack_taster.rb
> +  #   and passing the standardized parameters.
The 'taste_<suite>' is already done and documented. This is just a suggestion to make it even easier to add a suite to the tester.

2017-06-27 21:54 UTC, DesertBeagle commented on lib/openstack_taster.rb
> +  # @todo Don't crash when connection refused.
That was a comment left by @tolvstaa. I never saw this either.

2017-06-27 21:55 UTC, DesertBeagle commented on lib/openstack_taster.rb
> +  # @note This method blocks until the image is complete on the server.
This was another @tolvstaa coment, but I will rephrase it that way.

2017-06-28 16:52 UTC, DesertBeagle commented
@knightsamar Fixed!

2017-06-28 22:03 UTC, knightsamar approved these changes
Let's tackle the `tries` constant in a seperate PR and merge this for now.

2017-06-28 22:05 UTC, merged