Initial github issues template file
osuosl/openstack_taster pull request #30
Opened 2017-07-15 00:31 UTC by eldebrim

Will resolve #29. Is there anything else that we should expect from issue submissions?

2017-07-17 17:09 UTC, knightsamar reviewed
Thanks for making this.

Two more things we need to put here:

1. Recommend using `pastebin.osuosl.org` or some other pastebin service.

2. We should ask for their OpenStack version too.

2017-07-17 17:09 UTC, knightsamar commented on .github/ISSUE_TEMPLATE.md
> +1. All Openstack environment variables
"OpenStack"

2017-07-17 17:09 UTC, knightsamar commented on .github/ISSUE_TEMPLATE.md
> +3. The log files in your openstack_taster/logs directory
So openstack_taster will actually just create a `logs` directory. The `openstack_taster` parent dir is not required for running openstack_taster once it is installed as a gem.

2017-07-17 17:17 UTC, knightsamar requested changes

2017-07-17 17:17 UTC, knightsamar commented on .github/ISSUE_TEMPLATE.md
> +1. All Openstack environment variables
On second thoughts, we won't need these. Ideally, they should declare all the variables from README and `openstack_taster` should work when pointed to any OpenStack deployment.

2017-07-18 16:45 UTC, knightsamar requested changes

2017-07-18 16:45 UTC, knightsamar commented on .github/ISSUE_TEMPLATE.md
> +If possible, please include the following information in a pastebin such as `pastebin.osuosl.org` when submitting an issue:
The pastebin is good for logs and `gem list` only. Everything else can remain in the issue text.

Actually, I think they can also attach the log files to an issue. That or pastebin, anything is preferable over pasting things in the issue.

2017-07-18 23:37 UTC, knightsamar requested changes
Just some final changes and we should be good!

2017-07-18 23:37 UTC, knightsamar commented on .github/ISSUE_TEMPLATE.md
> +* The steps required to reprodocue the problem
*"reproduce" :)

2017-07-18 23:37 UTC, knightsamar commented on .github/ISSUE_TEMPLATE.md
> +* The output of using `gem list`
`using` can be dropped here.

2017-07-19 20:41 UTC, hodgiwabi approved these changes

2017-07-19 20:57 UTC, DesertBeagle commented
Should we write something about ensuring their environment variables are correct?

2017-07-19 21:00 UTC, knightsamar commented
@DesertBeagle I think it's safe to assume that they do have them correct, given that's the first instruction in the README. If we see a pattern later, we can do that.

2017-07-19 21:00 UTC, Codysseus approved these changes

2017-07-20 00:01 UTC, knightsamar approved these changes

2017-07-20 22:32 UTC, merged