@volume_service provides up to date information on volume attachment
osuosl/openstack_taster pull request #38
Opened 2017-07-26 18:16 UTC by DesertBeagle

Volume is a snapshot of the volume before attachment, so testing that for attachments won't work. Also, continues testing other volumes on attachment failure.

2017-07-26 18:47 UTC, DesertBeagle commented
@knightsamar Pushed commit!

2017-07-26 20:14 UTC, knightsamar commented
Works perfectly well on `CentOS 7.2 BE` and `CentOS 7.3 LE` ?

2017-07-26 20:42 UTC, DesertBeagle commented
@knightsamar Yup!: https://pastebin.osuosl.org/61631/

2017-07-26 20:52 UTC, knightsamar approved these changes

2017-07-26 20:52 UTC, knightsamar requested changes

2017-07-26 20:52 UTC, knightsamar commented on lib/openstack_taster.rb
> +        next # Returns from taste_volumes
Please change this comment!

2017-07-26 20:56 UTC, DesertBeagle commented
@knightsamar removed!

2017-07-26 21:07 UTC, knightsamar approved these changes

2017-07-27 18:26 UTC, knightsamar commented
Merging this before we release the gem.

2017-07-27 18:26 UTC, merged