Logger Refactor
osuosl/openstack_taster pull request #8
Opened 2017-06-06 19:44 UTC by DesertBeagle

### **This branch is branched off of #1, so it should not be merged until #1 is merged.**
This PR refactors the logger to use the Logger object to log files instead of writing to files directly.

2017-06-20 17:14 UTC, DesertBeagle commented
This logger refactor was created before the need for single image testing. The single image testing will be another PR.

2017-06-20 21:44 UTC, knightsamar requested changes
Did you have a successful test run ?

2017-06-20 21:44 UTC, knightsamar commented on lib/openstack_taster.rb
> +      error_log(instance_logger, 'error', 'Failed to create instance.', true)
Why is it `instance_logger` here while `instance.logger` elsewhere?

2017-06-20 21:44 UTC, knightsamar commented on lib/openstack_taster.rb
> +  def error_log(logger, level, message, dup_stdout = false, progname = nil)
If `progname` is for program name, let's call it `testuite_name` or something like that.

2017-06-20 21:44 UTC, knightsamar commented on lib/openstack_taster.rb
> +  def error_log(logger, level, message, dup_stdout = false, progname = nil)
Does the `dup_stdout` parameter still serve it's purpose?

2017-06-20 22:44 UTC, DesertBeagle commented on lib/openstack_taster.rb
> +      error_log(instance_logger, 'error', 'Failed to create instance.', true)
I can't add the logger to the instance object because it is a NilClass.

2017-06-20 22:46 UTC, DesertBeagle commented on lib/openstack_taster.rb
> +  def error_log(logger, level, message, dup_stdout = false, progname = nil)
This isn't necessarily used just for the test suites. For instance, with SSH errors. Maybe `context`?

2017-06-20 22:47 UTC, DesertBeagle commented on lib/openstack_taster.rb
> +  def error_log(logger, level, message, dup_stdout = false, progname = nil)
Yes, on the next line is `puts message if dup_stdout`.

2017-06-20 23:05 UTC, DesertBeagle commented
@knightsamar I was able to successfully get logger to work!

2017-06-21 16:22 UTC, knightsamar commented on lib/openstack_taster.rb
> +  def error_log(logger, level, message, dup_stdout = false, progname = nil)
Yep that sounds good

2017-06-21 18:32 UTC, DesertBeagle commented
@knightsamar Is there anything else you want me to change?

2017-06-21 20:50 UTC, ramereth approved these changes
LGTM

2017-06-21 20:58 UTC, knightsamar approved these changes

2017-06-21 20:59 UTC, merged